
# This sets the container image 
image:
  repository: 430695042840.dkr.ecr.us-east-1.amazonaws.com/project_a_kubernetes_backend
  pullPolicy: IfNotPresent
  tag: sha-97a323e
nameOverride: "backend"
fullnameOverride: "project-a-helm-backend"
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::430695042840:role/kube-SA-OIDC
# This is for setting Kubernetes Annotations to a Pod.
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
podLabels: {}
#defining pod level security... least privilledge and blast radius control
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 400
# This is for setting up a service
service:
  type: ClusterIP
  port: 8000
  label: backend-app
  portName: backend-http
resources:
  limits:
    cpu: 300m
    memory: 328Mi
  requests:
    cpu: 200m
    memory: 256Mi
# This is to setup the startup,liveness and readiness probes
startupProbe:
  httpGet:
    path: /health/ready
    port: http
  failureThreshold: 30
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 5
livenessProbe:
  httpGet:
    path: /health/live
    port: http
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 2
readinessProbe:
  httpGet:
    path: /health/ready
    port: http
  initialDelaySeconds: 20
  timeoutSeconds: 2
  periodSeconds: 5
# This section is for setting up autoscaling 
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70 #We scale pod when the cpu resource of the pods get to 70%
  targetMemoryUtilizationPercentage: 70 #we scale pods when the memory usage gets to 70% 
  stabilizeWindowSecondsScaleUp: 30
  selectPolicy: Max
  policiesUp:
    - type: Percent
      value: 50
      periodSeconds: 60
    - type: Pods
      value: 4
      periodSeconds: 60
  stabilizeWindowSecondsScaleDown: 300
  policiesDown:
    - type: Percent
      value: 20
      periodSeconds: 60
    - type: Pods
      value: 1
      periodSeconds: 60
servicemonitor:
  create: true
  name: project-a-servicemonitor-backend
  namespace: monitor
  labels: kube-prometheus-stack
  matchName: prod
