apiVersion: v1
kind: Service
metadata:
  name: {{ include "project_A_helm_backend.fullname" . }}
  labels:
    name: {{ .Values.service.label}}
    {{- include "project_A_helm_backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "project_A_helm_backend.selectorLabels" . | nindent 4 }}
